Settings:
  Items: true
  Mobs: false
  ExpOrb: true

# Interval in seconds
Interval: 300

Messages:
  Prefix: "[ClearLag]"
  Running: "{PREFIX} Entities will be cleared in {SECONDS} seconds"
  Cleared: "{PREFIX} {COUNT} entities cleared"

Times:
  - 60
  - 30
  - 15
  - 10
  - 3
  - 2
  - 1